In [1]:
import numpy as np

In [6]:
a = np.array([1,2,3,4])

In [7]:
print(a)

[1 2 3 4]


In [8]:
a.shape   #Defined column & row quantity

(4,)

In [9]:
b= np.array([[1,2,3,4],[0,0,0,0]])

In [10]:
b.shape

(2, 4)

In [11]:
print(b)

[[1 2 3 4]
 [0 0 0 0]]


In [16]:
d=np.array([[1234,1234,5432],[877,322,54]])

In [14]:
d.shape

(2, 3)

In [18]:
d.max() # Defined maxim quantity

5432

In [19]:
d.min() # Defined minimum quantity

54

In [21]:
f= np.array([[1,2,3,4],[2,4,6,8],[3,6,9,6]])

In [22]:
f.shape

(3, 4)

In [57]:
f

array([[1, 2, 3, 4],
       [2, 4, 6, 8],
       [3, 6, 9, 6]])

In [24]:
f.size # Defined total quantity

12

In [26]:
f.itemsize

4

In [27]:
f.dtype # Defined type

dtype('int32')

In [28]:
g = np.array([1.9,3.9,4.9],dtype=float)

In [29]:
g.dtype

dtype('float64')

In [31]:
g.itemsize

8

In [32]:
type(g)

numpy.ndarray

In [33]:
f

array([[1, 2, 3, 4],
       [2, 4, 6, 8],
       [3, 6, 9, 6]])

In [34]:
f.ndim    # ndim means to calculate dim. i.e. 2D,3D....

2

In [35]:
f.reshape(4,3)

array([[1, 2, 3],
       [4, 2, 4],
       [6, 8, 3],
       [6, 9, 6]])

In [36]:
o = np.arange(15) # arrange means to calculate range

In [37]:
o

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
o = np.arange(15,33)

In [39]:
o

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32])

In [40]:
o.shape

(18,)

In [60]:
i=np.arange(8)

In [61]:
i

array([0, 1, 2, 3, 4, 5, 6, 7])

In [59]:
i.shape

(8,)

In [43]:
f

array([[1, 2, 3, 4],
       [2, 4, 6, 8],
       [3, 6, 9, 6]])

In [44]:
f.ravel()

array([1, 2, 3, 4, 2, 4, 6, 8, 3, 6, 9, 6])

In [52]:
p = np.zeros([3])

In [49]:
p

array([0., 0., 0.])

In [53]:
p = np.ones([3])

In [54]:
p

array([1., 1., 1.])

In [55]:
z = np.arange(0,51,5)

In [56]:
z

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])