In [4]:
import numpy as np

In [5]:
a=np.array([123,234,345])

In [6]:
a

array([123, 234, 345])

In [7]:
a.shape

(3,)

In [8]:
a.max()

345

In [9]:
a.min()

123

In [10]:
b=np.array([[12,34,45,56],[76,45,87,98]])

In [11]:
b

array([[12, 34, 45, 56],
       [76, 45, 87, 98]])

In [12]:
b.reshape(4,2)

array([[12, 34],
       [45, 56],
       [76, 45],
       [87, 98]])

In [13]:
b.ndim

2

In [14]:
b.shape

(2, 4)

In [15]:
b.dtype

dtype('int32')

In [16]:
b=np.array([[12,34,45,56],[76,45,87,98]],dtype='int64')

In [17]:
b.dtype

dtype('int64')

In [18]:
b=np.array([[12,34,45,56],[76,45,87,98]],dtype='float32')

In [19]:
b.dtype

dtype('float32')

In [20]:
b.itemsize

4

In [21]:
b.reshape(4,2)

array([[12., 34.],
       [45., 56.],
       [76., 45.],
       [87., 98.]], dtype=float32)

In [22]:
b=np.arange(16)

In [23]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [24]:
b=np.zeros(4)

In [25]:
b

array([0., 0., 0., 0.])

In [26]:
b=np.ones(5)

In [27]:
b

array([1., 1., 1., 1., 1.])

In [28]:
b=np.ones(5,dtype='int32')

In [29]:
b

array([1, 1, 1, 1, 1])

In [30]:
b=np.ones(5,dtype='int')

In [31]:
b

array([1, 1, 1, 1, 1])

In [32]:
c=np.array([16,18,22,48])

In [33]:
c

array([16, 18, 22, 48])

In [34]:
d=np.array([24,12,36,44])

In [35]:
d

array([24, 12, 36, 44])

In [36]:
x=c*d

In [37]:
x

array([ 384,  216,  792, 2112])

In [38]:
x=c*4

In [39]:
x

array([ 64,  72,  88, 192])

In [40]:
x=c-2

In [41]:
x

array([14, 16, 20, 46])

In [42]:
x=c+2
print(x)

[18 20 24 50]


In [43]:
x=c/2
print(x)

[ 8.  9. 11. 24.]


In [44]:
x=c//2
print(x)

[ 8  9 11 24]


In [45]:
x=c%2
print(x)

[0 0 0 0]


In [46]:
x=d*2

In [47]:
x

array([48, 24, 72, 88])

In [48]:
x=c-d
print(c)

[16 18 22 48]


In [49]:
c


array([16, 18, 22, 48])

In [50]:
d

array([24, 12, 36, 44])

In [51]:
np.add(c,d)

array([40, 30, 58, 92])

In [52]:
x=d-c
print(x)

[ 8 -6 14 -4]


In [53]:
x=c**2

In [54]:
x

array([ 256,  324,  484, 2304], dtype=int32)

In [55]:
x=c^2

In [56]:
x

array([18, 16, 20, 50], dtype=int32)

In [57]:
x=np.random.rand(3,2)
print(x)

[[0.57625149 0.47124317]
 [0.12449032 0.6166886 ]
 [0.39401069 0.28251353]]


In [58]:
x=np.random.randint(2,220)

In [59]:
x

50

In [60]:
x=np.random.randint(2,220,100)

In [61]:
x

array([ 27, 214,  69,  59, 202,   3, 219,   2, 206,  25, 165, 112,  60,
        39, 101,  16, 107, 100,  15, 212, 114,  65,  36,  22, 174,  48,
       109, 178, 185, 113,  46, 124, 161,  75, 136, 158, 159,  65, 152,
        52,  54,  18, 117,  51,  74, 164, 200, 219, 106, 170,  20, 184,
        13, 187,   6, 155,   5, 178,  14, 159, 190, 136,  91, 197, 101,
       177,  91,  85, 182,  78, 119, 205, 152,  26, 207,  94, 134,  20,
       211, 195,  49, 102,  78, 214,  50,  30, 206,  32,  74, 182,  13,
        24, 186,  78,  62,  25,  70,  96, 158, 195])

In [62]:
x=np.random.randint(2,220,1)

In [63]:
x

array([26])

In [64]:
x= np.random.randint(1,100, size=(4,5))
x

array([[35, 42, 83, 64, 94],
       [28, 53, 49, 76, 35],
       [63, 69, 93, 73, 13],
       [24, 99, 26, 47, 89]])

In [66]:
x=np.random.randint(4,200,101)

In [67]:
x

array([185,  36,  82,  92,  82, 182, 162,  13, 109,  15,  20,  13, 169,
       191, 110, 150,  26,  64,  82, 111, 103,  50,  77,  12,  42, 131,
       181, 196, 115,  37,  12, 112,  67, 118, 147, 140,  72,  77, 176,
        51, 103,  83, 151,  88, 119, 120, 110,  37,  93,  34, 171,  74,
       114, 114,  40,  53, 141,  38, 146,  50,  24,  12, 178, 182, 181,
        81, 160, 146, 164,   6, 144,  33, 169, 124,   9, 113, 186, 174,
        30,  53, 189, 177, 101, 113, 123, 161,  55,  86, 116, 140,  17,
       105, 143,  27, 131, 193, 147,  65,  14,  81,  57])

In [68]:
x=np.random.randint(1,50, size=(5,5))

In [69]:
x

array([[12, 17, 41, 21, 10],
       [40, 19, 49,  9, 44],
       [48,  7, 23, 25, 38],
       [37, 26,  5, 35, 44],
       [47,  1, 15, 34, 20]])

In [70]:
x=np.random.randn(1,50)

In [71]:
x

array([[-1.65016484, -1.27547025,  1.11276445, -0.78627947, -0.70382939,
        -0.08256909,  1.34047306, -1.23633986,  0.43082049, -0.65573717,
         0.07045178,  1.84411849,  0.39063034,  0.32097011,  0.39930971,
         0.09930373,  0.45518041,  0.97772016, -0.7984497 , -1.12560741,
        -0.42432422, -1.18638784,  1.09323887, -0.78172823, -0.18625659,
        -0.19249648,  0.13582335,  1.65725967, -0.44855335,  0.62295468,
        -0.77723579,  1.95670962,  2.12788401,  0.3077165 , -0.95081418,
        -1.21389857, -2.07843934, -0.25607668, -2.02866731, -0.1482874 ,
         0.10383767,  0.25477741, -0.71200019, -0.89328376, -0.73025638,
        -1.10777748,  0.0569854 ,  0.30451327, -0.08101179, -0.11745507]])

In [117]:
x=np.random.randint(1,50,dtype='int32')

In [118]:
x

33

In [136]:
x=np.random.randint(1,50,size=[6,5])

In [137]:
x

array([[16, 37, 19,  3, 42],
       [22, 17, 47, 10, 22],
       [13, 43, 23, 33, 46],
       [ 3, 26,  2, 38,  9],
       [26, 15, 34,  3, 45],
       [46,  2, 14, 30, 36]])

In [72]:
x=np.random.randnint(-1,50)

AttributeError: module 'numpy.random' has no attribute 'randnint'

In [123]:
x=np.random.randint(-50,-1,50)

In [124]:
x

array([-32,  -5,  -4, -10, -34, -12, -16, -16, -11,  -8, -33, -45, -28,
        -6, -46,  -3, -20,  -3, -17, -42, -11, -18, -47, -25, -46, -15,
        -3, -28, -29, -41, -30, -46, -23, -13, -15, -41, -43, -43, -46,
       -26, -39, -42, -25, -26, -17, -40,  -9, -46, -49, -18])

In [86]:
x=np.random.randint(1,50, dtype='int32')

In [87]:

x

4

In [88]:
ab=np.array([43,56,78,98,34,62,88,84,44])

In [89]:
ab

array([43, 56, 78, 98, 34, 62, 88, 84, 44])

In [90]:
ab.size

9

In [91]:
ab[0]

43

In [92]:
ab[8]

44

In [93]:
ab[-1]

44

In [94]:
ab[-5]

34

In [95]:
ab[1:4]

array([56, 78, 98])

In [96]:
ab[2:5]

array([78, 98, 34])

In [97]:
ab[2:]

array([78, 98, 34, 62, 88, 84, 44])

In [98]:
ab[:4]

array([43, 56, 78, 98])

In [99]:
ab[-4:-1]

array([62, 88, 84])

In [100]:
ab[-1:-5]

array([], dtype=int32)

In [101]:
ab[-3:]

array([88, 84, 44])

In [102]:
ab[:-3]

array([43, 56, 78, 98, 34, 62])

In [103]:
ab[:]

array([43, 56, 78, 98, 34, 62, 88, 84, 44])

In [104]:
x=np.array([2,4,8,12,44,88])

In [105]:
x

array([ 2,  4,  8, 12, 44, 88])

In [106]:
np.sqrt(x)

array([1.41421356, 2.        , 2.82842712, 3.46410162, 6.63324958,
       9.38083152])

In [107]:
np.add(x+ab)

ValueError: operands could not be broadcast together with shapes (6,) (9,) 

In [108]:
bc=np.array([12,22,44,55,64,66])

In [109]:
bc

array([12, 22, 44, 55, 64, 66])

In [111]:
np.add(x,bc)

array([ 14,  26,  52,  67, 108, 154])

In [112]:
x=np.array([[44,87,np.nan,78],[98,np.nan,54,99]])

In [113]:
x

array([[44., 87., nan, 78.],
       [98., nan, 54., 99.]])

In [114]:
np.exp(x)

array([[1.28516001e+19, 6.07603023e+37,            nan, 7.49841700e+33],
       [3.63797095e+42,            nan, 2.83075330e+23, 9.88903032e+42]])